USE [master]
GO

/****** Object:  Database [funds]    Script Date: 08/07/2019 22:01:26 ******/
CREATE DATABASE [funds]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'funds', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\funds.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'funds_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\funds_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [funds].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [funds] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [funds] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [funds] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [funds] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [funds] SET ARITHABORT OFF 
GO

ALTER DATABASE [funds] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [funds] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [funds] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [funds] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [funds] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [funds] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [funds] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [funds] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [funds] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [funds] SET  ENABLE_BROKER 
GO

ALTER DATABASE [funds] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [funds] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [funds] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [funds] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [funds] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [funds] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [funds] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [funds] SET RECOVERY FULL 
GO

ALTER DATABASE [funds] SET  MULTI_USER 
GO

ALTER DATABASE [funds] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [funds] SET DB_CHAINING OFF 
GO

ALTER DATABASE [funds] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [funds] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [funds] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [funds] SET QUERY_STORE = OFF
GO

ALTER DATABASE [funds] SET  READ_WRITE 
GO

USE [funds]
GO

IF OBJECT_ID(N'[__EFMigrationsHistory]') IS NULL
BEGIN
    CREATE TABLE [__EFMigrationsHistory] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
    );
END;

GO

CREATE TABLE [Funds] (
    [Id] bigint NOT NULL IDENTITY,
    [Name] nvarchar(30) NOT NULL,
    [Description] nvarchar(255) NOT NULL,
    CONSTRAINT [PK_Funds] PRIMARY KEY ([Id])
);

GO

CREATE TABLE [ValueFund] (
    [Id] bigint NOT NULL IDENTITY,
    [DateFund] datetime2 NOT NULL,
    [Value] int NOT NULL,
    [FundId] bigint NOT NULL,
    CONSTRAINT [PK_ValueFund] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_ValueFund_Funds_FundId] FOREIGN KEY ([FundId]) REFERENCES [Funds] ([Id]) ON DELETE CASCADE
);

GO

CREATE INDEX [IX_ValueFund_FundId] ON [ValueFund] ([FundId]);

GO

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20190708153419_InitialMigration', N'2.2.4-servicing-10062');

GO

