// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using funds_api.Persistence.Contexts;

namespace funds_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190708153419_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("test_accudelta.Implementation.Models.Fund", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Funds");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "First fund",
                            Name = "Fund1"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Second fund",
                            Name = "Fund2"
                        });
                });

            modelBuilder.Entity("test_accudelta.Implementation.Models.ValueFund", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateFund");

                    b.Property<long>("FundId");

                    b.Property<int>("Value");

                    b.HasKey("Id");

                    b.HasIndex("FundId");

                    b.ToTable("ValueFund");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DateFund = new DateTime(2019, 7, 8, 15, 34, 19, 111, DateTimeKind.Utc).AddTicks(35),
                            FundId = 1L,
                            Value = 100
                        },
                        new
                        {
                            Id = 2L,
                            DateFund = new DateTime(2019, 7, 8, 15, 34, 19, 111, DateTimeKind.Utc).AddTicks(1923),
                            FundId = 2L,
                            Value = 200
                        });
                });

            modelBuilder.Entity("test_accudelta.Implementation.Models.ValueFund", b =>
                {
                    b.HasOne("test_accudelta.Implementation.Models.Fund")
                        .WithMany("Values")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
